### ISSUE TITLE
Deploy Landing page to cloudflare pages

### ISSUE THREAD

**Issue by LarsFlieger** [dopeshot/nextparty.io-landing#2]

**Comment by LarsFlieger** [comment]
- stable branch added as version in production

**Comment by coffemakingtoaster** [comment]
Does this include setting the cloudflare DNS entry to direct to cloudflare pages?
@LarsFlieger

**Comment by coffeemakingtoaster** [comment]
Does this include setting the cloudflare DNS entry to direct to cloudflare pages?
@LarsFlieger

**Comment by LarsFlieger** [comment]
> Does this include setting the cloudflare DNS entry to direct to cloudflare pages? @LarsFlieger

Yes. These are the entries:


Type | Name | Content
-- | -- | -- 
CNAME | nextparty.io | truth-or-dare-landing.pages.dev 
CNAME | www | truth-or-dare-landing.pages.dev

However I came up with one issue this night: 
Currently you can browse the site with www and without. We have to redirect from www to without or say one of them is the prefered way. Because google will index booth variants and we will have duplicated sites than. 

I'll follow this tutorial: https://developers.cloudflare.com/pages/how-to/www-redirect/
and ping you when it's done!

**Comment by coffeemakingtoaster** [comment]
Is this a seperate issue (workload wise) or part of this one?
if its the ladder remove automatic close from MR so you can merge it without closing the issue prematurely.

**Comment by LarsFlieger** [comment]
> Is this a seperate issue (workload wise) or part of this one? if its the ladder remove automatic close from MR so you can merge it without closing the issue prematurely.

It does not require any modification in the repo only cloudflare. But it's done. Redirect should be working in a few hours.


```
https://www.nextparty.io/ => https://nextparty.io/
https://www.nextparty.io/example => https://nextparty.io/example
```

**Comment by coffemakingtoaster** [comment]
From my side you are good to merge then

**Comment by LarsFlieger** [comment]
Since there is no progress here (www is still working fine). I removed the DNS record for the redirect. Let's wait till the www fails completely and start again than.
